services:
  frontend:
    image: beer-quest-frontend
    build: frontend
    depends_on:
      - backend
    ports:
      - 3000:3000

  backend:
    image: beer-quest-backend
    build: backend
    ports:
      - 5153:8080